In [1]:
# ================================
# HUMAN RESOURCE DATA ANALYSIS
# BASIC CLEANING + FEATURE ENGINEERING
# ================================

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("E:\AAA_projects\HR\existing.csv")

# ================================
# 1. CHECK DATATYPES
# ================================
print(df.dtypes)

EmpID                       object
Age                          int64
AgeGroup                    object
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
SalarySlab                  object
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
dtype: object

In [2]:
# 2. CONVERT COLUMN NAMES TO LOWERCASE + UNDERSCORE FORMAT
# ================================
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

In [3]:
df.columns

Index(['empid', 'age', 'agegroup', 'attrition', 'businesstravel', 'dailyrate',
       'department', 'distancefromhome', 'education', 'educationfield',
       'employeecount', 'employeenumber', 'environmentsatisfaction', 'gender',
       'hourlyrate', 'jobinvolvement', 'joblevel', 'jobrole',
       'jobsatisfaction', 'maritalstatus', 'monthlyincome', 'salaryslab',
       'monthlyrate', 'numcompaniesworked', 'over18', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'standardhours', 'stockoptionlevel', 'totalworkingyears',
       'trainingtimeslastyear'],
      dtype='object')

In [4]:
# 3. CHECK NULL VALUES
# ================================
print(df.isnull().sum())

empid                       0
age                         0
agegroup                    0
attrition                   0
businesstravel              0
dailyrate                   0
department                  0
distancefromhome            0
education                   0
educationfield              0
employeecount               0
employeenumber              0
environmentsatisfaction     0
gender                      0
hourlyrate                  0
jobinvolvement              0
joblevel                    0
jobrole                     0
jobsatisfaction             0
maritalstatus               0
monthlyincome               0
salaryslab                  0
monthlyrate                 0
numcompaniesworked          0
over18                      0
overtime                    0
percentsalaryhike           0
performancerating           0
relationshipsatisfaction    0
standardhours               0
stockoptionlevel            0
totalworkingyears           0
trainingtimeslastyear       0
dtype: int64

In [5]:
# 4. REMOVE DUPLICATES
# ================================
df.drop_duplicates(inplace=True)

In [7]:
# ================================
# 5. FEATURE ENGINEERING - NEW COLUMNS
# ================================

# Experience category
df['experience_category'] = pd.cut(
    df['totalworkingyears'],
    bins=[-1, 2, 5, 10, 20, 40],
    labels=['Fresher', 'Junior', 'Mid-Level', 'Senior', 'Expert']
)

# Income yearly
df['annual_income'] = df['monthlyincome'] * 12

# Salary efficiency
df['income_per_year_experience'] = df['monthlyincome'] / (df['totalworkingyears'] + 1)

# Distance category
df['distance_category'] = pd.cut(
    df['distancefromhome'],
    bins=[0, 5, 15, 30],
    labels=['Near', 'Moderate', 'Far']
)

# Satisfaction score combined
df['overall_satisfaction_score'] = (
    df['environmentsatisfaction'] +
    df['jobsatisfaction'] +
    df['relationshipsatisfaction']
)

# Promotion readiness indicator
df['promotion_ready'] = np.where(
    (df['performancerating'] >= 3) &
    (df['joblevel'] >= 2),
    'Yes',
    'No'
)

# Attrition risk score
df['attrition_risk_score'] = (
    df['overtime'].map({'Yes': 2, 'No': 0}) +
    (4 - df['jobsatisfaction']) +
    (4 - df['environmentsatisfaction'])
)

# Work stability score
df['work_stability_score'] = (
    df['totalworkingyears'] -
    df['numcompaniesworked']
)

In [8]:
df.columns

Index(['empid', 'age', 'agegroup', 'attrition', 'businesstravel', 'dailyrate',
       'department', 'distancefromhome', 'education', 'educationfield',
       'employeecount', 'employeenumber', 'environmentsatisfaction', 'gender',
       'hourlyrate', 'jobinvolvement', 'joblevel', 'jobrole',
       'jobsatisfaction', 'maritalstatus', 'monthlyincome', 'salaryslab',
       'monthlyrate', 'numcompaniesworked', 'over18', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'standardhours', 'stockoptionlevel', 'totalworkingyears',
       'trainingtimeslastyear', 'experience_category', 'annual_income',
       'income_per_year_experience', 'distance_category',
       'overall_satisfaction_score', 'promotion_ready', 'attrition_risk_score',
       'work_stability_score'],
      dtype='object')

In [9]:
# Analysis Starts 
#Promotion Ready Employees by Department
df.groupby('department')['promotion_ready'].value_counts()

department              promotion_ready
Human Resources         No                  33
                        Yes                 30
Research & Development  Yes                527
                        No                 434
Sales                   Yes                370
                        No                  76
Name: count, dtype: int64

In [11]:
#Work Stability by Age Group
df.groupby('agegroup')['work_stability_score'].mean()

agegroup
18-25     1.813008
26-35     5.521452
36-45     9.655983
46-55    16.654867
55+      16.382979
Name: work_stability_score, dtype: float64

In [12]:
#High Attrition Risk Employees
df[df['attrition_risk_score'] >= 5]

,empid,age,agegroup,attrition,businesstravel,dailyrate,department,distancefromhome,education,educationfield,...,totalworkingyears,trainingtimeslastyear,experience_category,annual_income,income_per_year_experience,distance_category,overall_satisfaction_score,promotion_ready,attrition_risk_score,work_stability_score
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,0,3,Fresher,22536,1878.000000,Near,8,No,6,-1
15,RM893,19,18-25,Yes,Non-Travel,504,Research & Development,10,3,Medical,...,1,2,Fresher,22308,929.500000,Moderate,5,No,7,0
21,RM690,20,18-25,Yes,Travel_Rarely,129,Research & Development,4,3,Technical Degree,...,1,2,Fresher,35676,1486.500000,Near,4,No,6,0
22,RM732,20,18-25,Yes,Travel_Rarely,1097,Research & Development,11,3,Medical,...,1,2,Fresher,31200,1300.000000,Moderate,6,No,5,0
30,RM358,21,18-25,Yes,Travel_Frequently,756,Sales,1,1,Technical Degree,...,3,3,Junior,26088,543.500000,Near,6,No,7,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463,RM1311,58,55+,No,Travel_Frequently,1216,Research & Development,15,4,Life Sciences,...,23,3,Expert,189444,657.791667,Moderate,6,Yes,6,21
1465,RM007,59,55+,No,Travel_Rarely,1324,Research & Development,3,3,Medical,...,12,3,Senior,32040,205.384615,Near,5,No,6,8
1466,RM064,59,55+,No,Travel_Rarely,1435,Sales,25,3,Life Sciences,...,28,3,Expert,91644,263.344828,Far,6,Yes,6,21
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,33,5,Expert,234792,575.470588,Moderate,6,Yes,6,28
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,10,1,Mid-Level,64860,491.363636,Far,6,Yes,6,2

In [13]:
# 7. SAVE CLEANED FILE
# ================================
df.to_csv(r"E:\AAA_projects\HR\proposed.csv", index=False)

In [15]:
!pip install mysql-connector-python pymysql sqlalchemy

import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Load cleaned file
df = pd.read_csv(r"E:\AAA_projects\HR\proposed.csv")

# MySQL connection
username = "root"
password = quote_plus("Password@123")
host = "127.0.0.1"
port = "3306"
database = "hr_project"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Upload to MySQL
df.to_sql("hr_data", engine, if_exists="replace", index=False)

# Verify upload
pd.read_sql("SELECT * FROM hr_data LIMIT 5;", engine)

Requirement already satisfied: mysql-connector-python in c:\users\ahama\anaconda3\lib\site-packages (9.5.0)
Requirement already satisfied: pymysql in c:\users\ahama\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\ahama\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ahama\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ahama\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

,empid,age,agegroup,attrition,businesstravel,dailyrate,department,distancefromhome,education,educationfield,...,totalworkingyears,trainingtimeslastyear,experience_category,annual_income,income_per_year_experience,distance_category,overall_satisfaction_score,promotion_ready,attrition_risk_score,work_stability_score
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,0,2,Fresher,17040,1420.0,Near,9,No,2,-1
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,0,2,Fresher,14400,1200.0,Moderate,8,No,1,-1
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,0,3,Fresher,22536,1878.0,Near,8,No,6,-1
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,0,2,Fresher,12612,1051.0,Near,10,No,2,-1
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,0,0,Fresher,22848,1904.0,Moderate,10,No,2,-1